### ISSUE TITLE
 import { AstraDB } from "@datastax/astra-db-ts";

### ISSUE THREAD

**Issue by Kiezgold** [codinginflow/nextjs-langchain-portfolio#1]
Hi all, can anybody assist with the following error: 

`TSError: ⨯ Unable to compile TypeScript:
src/lib/astradb.ts:1:10 - error TS2305: Module '"@datastax/astra-db-ts"' has no exported member 'AstraDB'.

1 import { AstraDB } from "@datastax/astra-db-ts";`

 "@datastax/astra-db-ts": "^1.0.2",

Thank you!

**Comment by Kiezgold** [comment]
Ab, in the Datastax repo I found the following: 

_ This README targets v1.0.0+, which introduces a whole new API. Click here for the pre-existing client readme._

**Comment by Kiezgold** [comment]
I got it:
astradb.ts:

`export async function getEmbeddingsCollection() {
  return new DataAPIClient(token).db(endpoint).collection(collection);
}`

generate.ts:
`(await getEmbeddingsCollection()).deleteAll({})`

**Comment by Kiezgold** [comment]
I got it:

astradb.ts:
`export async function getEmbeddingsCollection() { return new DataAPIClient(token).db(endpoint).collection(collection); }`

`collectionOptions: {
        checkExists: false,
        vector: {
          dimension: 1536,
          metric: "cosine",
        },
      },`

generate.ts:
`(await getEmbeddingsCollection()).deleteAll({})`

**Comment by akashhyap** [comment]
Thanks @Kiezgold and @codinginflow
